### PR TITLE
Add PSR-16 Exception Compatible Pool Wrapper

### PR DESCRIPTION
**Pull request by XedinUnknown**
This adds a wrapper that hides all non-PSR-16 exceptions, thus fixing #7.

### CODE REVIEW

**Comment by szepeviktor** [comment]
As I see, this will return true on success and throw an exception otherwise.

This is what you talked about in the issue.

**Comment by XedinUnknown** [comment]
I didn't quite understand. Yes, it will. Yes, I talked about it. Is it good? Does this PR solve the issue for you, @szepeviktor?

**Comment by szepeviktor** [comment]
Yes it does.
Let's merge it!

**Comment by szepeviktor** [comment]
BTW I classify throwing Exceptions as a home-made thing.

**Comment by XedinUnknown** [comment]
I've no idea what you mean by "home-made" in this context.

**Comment by szepeviktor** [comment]
> by "home-made" in this context.

that PSR-16 does not talk about Exceptions

But merge it anyway.

**Review by szepeviktor — APPROVED** [review]

**Comment by XedinUnknown** [comment]
Looks like you may have missed an important part of the changes in this PR, in which case I would like to clarify. I didn't remove the original exceptions; in fact, I enhanced them. What I did was add a wrapper that hides them. So, developers have the option to have proper structured error handling, or compatibility. It's in the readme and the changelog, if you want to take a look.

**Comment by szepeviktor** [comment]
Oh! I see.

**Review by mecha — APPROVED** [review]

**Pull request merged**
