### PR TITLE
Import global functions

### LINKED ISSUE #8: Import global WP function
e.g. in CachePool

```php
use function set_transient;
use function delete_transient;
use function get_transient;
use function get_option;
```

What do you think about it?

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered with `SlevomatCodingStandard.Namespaces.FullyQualifiedGlobalFunctions`

Fixes #8

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Not sure if it's necessary to import PHP-native global-namespace functions. Everyone already knows what they are.

**Comment by szepeviktor** [comment]
```php
namespace SpaceForceOne;

function sprintf($a)
{
  \sprintf($a);
}
```

This way sprintf also exists in global and SpaceForceOne namespace! 👨‍🚀

**Comment by szepeviktor** [comment]
PHP engine executes fully qualified function a bit faster

- \sprintf
- or use function sprintf

**Comment by XedinUnknown** [comment]
Yes, of course, when the function exists in the namespace, it should be disambiguated. But otherwise, there's no need for that.

About speed. This is not a factor here. What matters is correctness and readability. Hardware becomes cheaper, software becomes faster, compiler optimization becomes more sophisticated - every day, without your involvement; but your code, if written incorrectly, will not normalize and optimize itself on its own :)

**Comment by XedinUnknown** [comment]
Also, just because some rule from some standard reports this, doesn't mean it's actually a problem.

**Comment by szepeviktor** [comment]
Last time you wrote https://github.com/wp-oop/transient-cache/issues/8#issuecomment-614061828

I leave it up to you.

**Comment by XedinUnknown** [comment]
@szepeviktor, upon consulting my colleague, we have decided that we want to use imports for all functions. Would you be able to update this branch from the target branch please?

**Comment by szepeviktor** [comment]
Done.

**Review by XedinUnknown — APPROVED** [review]
LGTM. Thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
